---
name: Build_GPAC

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

env:
  CI_IMAGE_NAME: 'ghcr.io/cradle8810/ffmpeg-mp4box-image'

jobs:
  "build_mp4box":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: apt-get
        run: |
          chmod +x .github/workflows/apt-get_install.sh 
          sudo .github/workflows/apt-get_install.sh

      - name: git_clone
        run: |
          git clone --depth 1 https://github.com/gpac/gpac gpac_public
          git clone --depth 1 https://github.com/gpac/deps_unix

      - name: configure_dependency
        run: |
          cd deps_unix
          git submodule update --init --recursive --force --checkout
          ./build_all.sh linux

      - name: configure_gpac
        run: |
          cd ../gpac_public
          ./configure --static-mp4box

      - name: make_gpac
        run: |
          make -j 2

      - name: make_deb_package
          make deb
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mp4box-package
          path: '*.deb'


  "build_dockerfile":
    needs: [build_mp4box]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Kick Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/crazy-max/ghaction-docker-meta#latest-tag
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.CI_IMAGE_NAME }}

      # https://github.com/marketplace/actions/docker-login#github-container-registry
      # Make your access key following this instructions, and add access key as $CR_PAT on Repository Secrets
        # https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}